# Generated by Django 5.1.1 on 2024-09-26 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_runner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='newapp.musician'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(help_text='Nhập tên album', max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(help_text='Nhập số sao đánh giá album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(help_text='Nhập ngày phát hành album'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(help_text='Nhập tên đầu tiên của nhạc sĩ', max_length=50),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.CharField(help_text='Nhập loại nhạc cụ', max_length=100),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(help_text='Nhập họ của nhạc sĩ', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Nhập tên của người', max_length=60),
        ),
        migrations.AlterField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], help_text='Chọn kích thước áo', max_length=1),
        ),
    ]
