# Generated by Django 5.1.1 on 2024-09-26 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_fruit_alter_album_artist_alter_album_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='newapp.musician', verbose_name='Nhạc sĩ'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(help_text='Nhập tên album', max_length=100, verbose_name='Tên album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(help_text='Nhập số sao đánh giá album', verbose_name='Số sao đánh giá'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(help_text='Nhập ngày phát hành album', verbose_name='Ngày phát hành'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(help_text='Nhập tên của loại trái cây', max_length=100, primary_key=True, serialize=False, verbose_name='Tên loại trái cây'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(help_text='Nhập tên đầu tiên của nhạc sĩ', max_length=50, verbose_name='Tên đầu tiên của nhạc sĩ'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.CharField(help_text='Nhập loại nhạc cụ', max_length=100, verbose_name='Loại nhạc cụ'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(help_text='Nhập họ của nhạc sĩ', max_length=50, verbose_name='Họ của nhạc sĩ'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Nhập tên của người', max_length=60, verbose_name='Tên người'),
        ),
        migrations.AlterField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], help_text='Chọn kích thước áo', max_length=1, verbose_name='Kích thước áo'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='medal',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], default='GOLD', help_text='Chọn loại huy chương (nếu có)', max_length=10, verbose_name='Loại huy chương'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='name',
            field=models.CharField(help_text='Nhập tên của vận động viên', max_length=60, verbose_name='Tên vận động viên'),
        ),
    ]
