# Generated by Django 5.1.1 on 2024-09-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_album_artist_alter_album_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(help_text='Nhập tên của loại trái cây', max_length=100, verbose_name='Tên loại trái cây'),
        ),
    ]
