# Generated by Django 5.1.1 on 2024-09-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_ox_personwithstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Tên'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên'),
        ),
    ]
